// AUTO-GENERATED by: supabase gen types typescript --local > packages/types/src/database.types.ts
// DO NOT edit by hand. Re-run the command above after any schema migration.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string | null
          display_name: string | null
          avatar_url: string | null
          sport_pref: 'soccer' | 'basketball' | null
          role: 'fan' | 'admin'
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username?: string | null
          display_name?: string | null
          avatar_url?: string | null
          sport_pref?: 'soccer' | 'basketball' | null
          role?: 'fan' | 'admin'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string | null
          display_name?: string | null
          avatar_url?: string | null
          sport_pref?: 'soccer' | 'basketball' | null
          role?: 'fan' | 'admin'
          created_at?: string
          updated_at?: string
        }
      }
      sports: {
        Row: {
          id: string
          name: 'soccer' | 'basketball'
          display: string
          icon_url: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: 'soccer' | 'basketball'
          display: string
          icon_url?: string | null
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: 'soccer' | 'basketball'
          display?: string
          icon_url?: string | null
          is_active?: boolean
          created_at?: string
        }
      }
      teams: {
        Row: {
          id: string
          sport_id: string
          name: string
          short_name: string | null
          logo_url: string | null
          country: string | null
          league: string | null
          external_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          sport_id: string
          name: string
          short_name?: string | null
          logo_url?: string | null
          country?: string | null
          league?: string | null
          external_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          sport_id?: string
          name?: string
          short_name?: string | null
          logo_url?: string | null
          country?: string | null
          league?: string | null
          external_id?: string | null
          created_at?: string
        }
      }
      players: {
        Row: {
          id: string
          team_id: string
          name: string
          position: string | null
          photo_url: string | null
          external_id: string | null
          is_featured: boolean
          created_at: string
        }
        Insert: {
          id?: string
          team_id: string
          name: string
          position?: string | null
          photo_url?: string | null
          external_id?: string | null
          is_featured?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          team_id?: string
          name?: string
          position?: string | null
          photo_url?: string | null
          external_id?: string | null
          is_featured?: boolean
          created_at?: string
        }
      }
      games: {
        Row: {
          id: string
          sport_id: string
          home_team_id: string
          away_team_id: string
          scheduled_at: string
          status: 'scheduled' | 'live' | 'finished' | 'cancelled'
          outcome: 'home_win' | 'away_win' | 'draw' | null
          home_score: number | null
          away_score: number | null
          venue: string | null
          external_id: string | null
          week_start: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          sport_id: string
          home_team_id: string
          away_team_id: string
          scheduled_at: string
          status?: 'scheduled' | 'live' | 'finished' | 'cancelled'
          outcome?: 'home_win' | 'away_win' | 'draw' | null
          home_score?: number | null
          away_score?: number | null
          venue?: string | null
          external_id?: string | null
          week_start: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          sport_id?: string
          home_team_id?: string
          away_team_id?: string
          scheduled_at?: string
          status?: 'scheduled' | 'live' | 'finished' | 'cancelled'
          outcome?: 'home_win' | 'away_win' | 'draw' | null
          home_score?: number | null
          away_score?: number | null
          venue?: string | null
          external_id?: string | null
          week_start?: string
          created_at?: string
          updated_at?: string
        }
      }
      team_historical_stats: {
        Row: {
          id: string
          team_id: string
          total_games: number
          wins: number
          losses: number
          draws: number
          avg_possession: number | null
          updated_at: string
        }
        Insert: {
          id?: string
          team_id: string
          total_games?: number
          wins?: number
          losses?: number
          draws?: number
          avg_possession?: number | null
          updated_at?: string
        }
        Update: {
          id?: string
          team_id?: string
          total_games?: number
          wins?: number
          losses?: number
          draws?: number
          avg_possession?: number | null
          updated_at?: string
        }
      }
      check_ins: {
        Row: {
          id: string
          user_id: string
          game_id: string
          team_id: string
          phase: 'pre_game' | 'post_game'
          emotion: 'excited' | 'nervous' | 'anxious' | 'hopeful' | 'stressed' | 'calm' | 'happy' | 'devastated' | 'frustrated' | 'proud' | 'disappointed' | 'relieved'
          notes: string | null
          suggestion_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          game_id: string
          team_id: string
          phase: 'pre_game' | 'post_game'
          emotion: 'excited' | 'nervous' | 'anxious' | 'hopeful' | 'stressed' | 'calm' | 'happy' | 'devastated' | 'frustrated' | 'proud' | 'disappointed' | 'relieved'
          notes?: string | null
          suggestion_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          game_id?: string
          team_id?: string
          phase?: 'pre_game' | 'post_game'
          emotion?: 'excited' | 'nervous' | 'anxious' | 'hopeful' | 'stressed' | 'calm' | 'happy' | 'devastated' | 'frustrated' | 'proud' | 'disappointed' | 'relieved'
          notes?: string | null
          suggestion_id?: string | null
          created_at?: string
        }
      }
      suggestion_templates: {
        Row: {
          id: string
          phase: 'pre_game' | 'post_game'
          outcome: 'home_win' | 'away_win' | 'draw' | null
          emotion: 'excited' | 'nervous' | 'anxious' | 'hopeful' | 'stressed' | 'calm' | 'happy' | 'devastated' | 'frustrated' | 'proud' | 'disappointed' | 'relieved'
          text: string
          tone: string | null
          is_active: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          phase: 'pre_game' | 'post_game'
          outcome?: 'home_win' | 'away_win' | 'draw' | null
          emotion: 'excited' | 'nervous' | 'anxious' | 'hopeful' | 'stressed' | 'calm' | 'happy' | 'devastated' | 'frustrated' | 'proud' | 'disappointed' | 'relieved'
          text: string
          tone?: string | null
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          phase?: 'pre_game' | 'post_game'
          outcome?: 'home_win' | 'away_win' | 'draw' | null
          emotion?: 'excited' | 'nervous' | 'anxious' | 'hopeful' | 'stressed' | 'calm' | 'happy' | 'devastated' | 'frustrated' | 'proud' | 'disappointed' | 'relieved'
          text?: string
          tone?: string | null
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      user_favorite_teams: {
        Row: {
          user_id: string
          team_id: string
        }
        Insert: {
          user_id: string
          team_id: string
        }
        Update: {
          user_id?: string
          team_id?: string
        }
      }
    }
    Views: {
      game_emotion_summary: {
        Row: {
          game_id: string | null
          team_id: string | null
          phase: 'pre_game' | 'post_game' | null
          emotion: 'excited' | 'nervous' | 'anxious' | 'hopeful' | 'stressed' | 'calm' | 'happy' | 'devastated' | 'frustrated' | 'proud' | 'disappointed' | 'relieved' | null
          fan_count: number | null
        }
      }
      game_team_participants: {
        Row: {
          game_id: string | null
          team_id: string | null
          phase: 'pre_game' | 'post_game' | null
          participant_count: number | null
        }
      }
    }
    Functions: Record<string, never>
    Enums: {
      sport_type: 'soccer' | 'basketball'
      game_status: 'scheduled' | 'live' | 'finished' | 'cancelled'
      game_outcome: 'home_win' | 'away_win' | 'draw'
      check_in_phase: 'pre_game' | 'post_game'
      emotion_type: 'excited' | 'nervous' | 'anxious' | 'hopeful' | 'stressed' | 'calm' | 'happy' | 'devastated' | 'frustrated' | 'proud' | 'disappointed' | 'relieved'
      app_role: 'fan' | 'admin'
    }
  }
}
